---
output: build/test

version: v1.1.3

data_pack:
  load:
    - src
  name: "[Test] {{ project_name | capitalize }} ({{ project_version }})"
  description: ''
  pack_format: 7

pipeline:
  - mecha
  - iredsc.counter
  - iredsc.message_format

meta:
  namespace:
    pack: "aeo"
    messages: "messages"
  mecha:
    keep_comments: true
